apiVersion: v1
kind: Template
labels:
  template: f8a-graph-cve-sync
metadata:
  name: f8a-graph-cve-sync
  annotations:
    description: f8a-graph-cve-sync
objects:
- apiVersion:  batch/v1
  kind: CronJob
  metadata:
    name: f8a-graph-cve-sync
    annotations:
      description: f8a-graph-cve-sync
  spec:
    successfulJobsHistoryLimit: 4
    failedJobsHistoryLimit: 0
    concurrencyPolicy: "Forbid"
    schedule: "${CRON_SCHEDULE}"
    jobTemplate:
      spec:
        template:
          spec:
            restartPolicy: Never
            containers:
            - name: f8a-graph-cve-sync
              image: "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${IMAGE_TAG}"
              env:
                - name: SYNC_MODE
                  value: "${SYNC_MODE}"
                - name: DRY_RUN
                  value: "${DRY_RUN}"
                - name: SNYK_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: snyk-secrets
                      key: token
                - name: BAYESIAN_GREMLIN_HTTPINGESTION_SERVICE_HOST
                  value: "${GREMLIN_HOST}"
                - name: BAYESIAN_GREMLIN_HTTPINGESTION_SERVICE_PORT
                  value: "${GREMLIN_PORT}"
                - name: SNYK_CUSTOM_MODE
                  value: "${SNYK_CUSTOM_MODE}"
                - name: SNYK_URL
                  value: "${SNYK_URL}"
                - name: SNYK_INGESTION_FORCE_RUN
                  value: "${SNYK_INGESTION_FORCE_RUN}"
                - name: SNYK_INGESTION_RUN_TIME
                  value: "${SNYK_INGESTION_RUN_TIME}"
                - name: SNYK_DELTA_FEED_OFFSET
                  value: "${SNYK_DELTA_FEED_OFFSET}"
                - name: SELECTIVE_ECOSYSTEM_SNYK_SYNC
                  value: "${SELECTIVE_ECOSYSTEM_SNYK_SYNC}"
                - name: SNYK_DELTA_FEED_MODE
                  value: "${SNYK_DELTA_FEED_MODE}"
                - name: SNYK_DRY_RUN
                  value: "${SNYK_DRY_RUN}"
                - name: DISABLE_SNYK_SYNC_OPERATION
                  value: "${DISABLE_SNYK_SYNC_OPERATION}"
                - name: DISABLE_SNYK_INGESTION_RETRY
                  value: "${DISABLE_SNYK_INGESTION_RETRY}"
                - name: COMPLETE_VULN_MODE
                  value: "${COMPLETE_VULN_MODE}"
                - name: DISABLE_VULN_MODE
                  value: "${DISABLE_VULN_MODE}"
                - name: SNYK_ORG_ID
                  valueFrom:
                    secretKeyRef:
                      name: snyk-secrets
                      key: orgid
                - name: REPORT_BUCKET_NAME
                  valueFrom:
                    secretKeyRef:
                      name: developer-analytics-audit-report-s3
                      key: bucket
                - name: AWS_S3_SECRET_ACCESS_KEY_REPORT_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: aws
                      key: s3-secret-access-key
                - name: AWS_S3_ACCESS_KEY_ID_REPORT_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: aws
                      key: s3-access-key-id
                - name: AWS_S3_REGION
                  valueFrom:
                    configMapKeyRef:
                      name: bayesian-config
                      key: aws-default-region
                - name: GITHUB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: worker
                      key: github-token
              resources:
                requests:
                  memory: ${MEMORY_REQUEST}
                  cpu: ${CPU_REQUEST}
                limits:
                  memory: ${MEMORY_LIMIT}
                  cpu: ${CPU_LIMIT}
parameters:
- description: Docker registry
  displayName: Docker registry
  required: true
  name: DOCKER_REGISTRY
  value: "quay.io"

- description: Docker image
  displayName: Docker image
  required: true
  name: DOCKER_IMAGE
  value: "openshiftio/fabric8-analytics-graph-cve-sync"

- description: Image tag
  displayName: Image tag
  required: true
  name: IMAGE_TAG
  value: "latest"

- description: Sync mode
  displayName: Sync mode
  required: true
  name: SYNC_MODE
  value: "diff"

- description: Dry run
  displayName: Dry run
  required: true
  name: DRY_RUN
  value: "false"

- description: Ingest only the delta feed from snyk
  displayName: Snyk delta feed mode
  required: true
  name: SNYK_DELTA_FEED_MODE
  value: "true"

- description: Either to run at 00 06 12 or 18 hours
  displayName: Snyk ingestion run time
  required: true
  name: SNYK_INGESTION_RUN_TIME
  value: "none"

- description: Delta feed days offset
  displayName: Offset value for delta feed
  required: true
  name: SNYK_DELTA_FEED_OFFSET
  value: "1"

- description: Forcefully start a snyk ingestion at any time of the day
  displayName: Snyk ingestion mode
  required: true
  name: SNYK_INGESTION_FORCE_RUN
  value: "false"

- description: Disable the entire snyk sync operation
  displayName: Disable snyk sync
  required: true
  name: DISABLE_SNYK_SYNC_OPERATION
  value: "false"

- description: Dry run mode for snyc ingestion
  displayName: Snyk dry run mode
  required: true
  name: SNYK_DRY_RUN
  value: "false"

- description: Select a particular ecosystem for sync
  displayName: provide the ecosystem java js python golang
  required: true
  name: SELECTIVE_ECOSYSTEM_SNYK_SYNC
  value: "none"

- description: Enable or disable snyk ingestion retry
  displayName: Disable retry mechanism
  required: true
  name: DISABLE_SNYK_INGESTION_RETRY
  value: "false"

- description: Enable or disable snyk vulnerability mode
  displayName: Disable vulnerability mode
  required: true
  name: DISABLE_VULN_MODE
  value: "false"

- description: Enable or disable a complete vulnerability metadata file generation
  displayName: Enable or disable a complete vulnerability metadata file generation
  required: true
  name: COMPLETE_VULN_MODE
  value: "false"

- description: Snyk Url
  displayName: Snyk Url
  required: true
  name: SNYK_URL
  value: "https://api.snyk.io/rest/orgs/{}/intel_feed/application_premium?version=2022-09-29"

- description: Schedule
  displayName: Schedule
  required: true
  name: CRON_SCHEDULE
  value: "0 */6 * * *"

- description: CPU request
  displayName: CPU request
  required: true
  name: CPU_REQUEST
  value: "250m"

- description: CPU limit
  displayName: CPU limit
  required: true
  name: CPU_LIMIT
  value: "500m"

- description: Memory request
  displayName: Memory request
  required: true
  name: MEMORY_REQUEST
  value: "1024Mi"

- description: Memory limit
  displayName: Memory limit
  required: true
  name: MEMORY_LIMIT
  value: "2048Mi"

- description: Gremlin host
  displayName: Gremlin host
  required: true
  name: GREMLIN_HOST
  value: "bayesian-gremlin-httpingestion"

- description: Gremlin port
  displayName: Gremlin port
  required: true
  name: GREMLIN_PORT
  value: "8182"

- description: Run Snyk custom logic
  displayName: Run Snyk custom logic
  required: true
  name: SNYK_CUSTOM_MODE
  value: "false"
